services:
  frontend:
    image: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
  backend:
    image: backend
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
    ports:
      - 8080:8080
