services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
  backend:
    image: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=db_postgres
      - REQUEST_ORIGIN=http://localhost
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_postgres
    restart: unless-stopped
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  database:
