services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=db_postgres
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_postgres
    restart: unless-stopped
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
