FROM golang:1.24

WORKDIR /myproject

COPY . .

RUN go build && \ 
    adduser appuser && \ 
    rm -rf cache common controller go.mod go.sum pgconnection router

USER appuser

EXPOSE 8080

CMD ["./server"]