FROM node:16-alpine

WORKDIR /myapp
COPY . .
ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm install && \ 
    npm install -g serve && \ 
    adduser -D appuser && \
    npm run build && \ 
    rm -rf src

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]