FROM golang:1.24-alpine AS build-stage

WORKDIR /myproject

COPY . .

RUN go build && \ 
    rm -rf cache common controller go.mod go.sum pgconnection router

FROM scratch AS final-stage

COPY --from=build-stage /myproject/server /server

EXPOSE 8080

CMD ["./server"]