FROM ubuntu AS build-stage

WORKDIR /myapp

RUN apt update
RUN apt install -y curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt install -y nodejs

COPY . .

RUN npm install
ENV REACT_APP_BACKEND_URL=http://localhost/api
RUN npm run build


FROM node:16-alpine3.18

WORKDIR /myapp

RUN adduser -D appuser
RUN npm install -g serve

USER appuser

COPY --from=build-stage /myapp/build /myapp/build

CMD ["serve", "-s", "-l", "5000", "build"]